import Head from 'next/head'
import styles from '@/styles/Layout.module.css';
import Sidebar from '@/components/sidebar';
import Navbar from '@/components/navbar';
import WorkflowBar from '@/components/workflowBar';
import CardContainer from '@/components/cardContainer';
import Card from '@/components/card';
import Image from 'next/image';
import data from '../mock data/mockData';
import ToDo from '../mock data/todoData';

import { useState } from 'react';

export default function Home() {
  const [backlog, setBacklog] = useState(data);
  const [toDo, setTodo] = useState(ToDo);
  const [inProcess] = useState(ToDo);
  const [inReview] = useState(data);
  const [completed] = useState(data);


  console.log(data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap" rel="stylesheet" />
      </Head>
      <Sidebar />
      <Navbar />
      <div className={styles.content}>
        <div className={styles.action_bar}>
          <WorkflowBar />
        </div>
        <main className={styles.main}>
          <CardContainer title={'Backlog'} cardNo={backlog.length} >
            {backlog.map(i => (<Card key={i.title} {...i} />))}
          </CardContainer>
          <CardContainer title={'To Do'} cardNo={toDo.length} >
            {toDo.map(i => (<Card key={i.title} {...i} />))}
          </CardContainer>
          <CardContainer title={'In Process'} cardNo={35} >
            {inProcess.map(i => (<Card key={i.title} {...i} />))}
          </CardContainer>
          <CardContainer title={'In Review'} cardNo={5} >
            {inReview.map(i => (<Card key={i.title} {...i} />))}
          </CardContainer>
          <CardContainer title={'Completed'} cardNo={1} >
            {completed.map(i => (<Card key={i.title} {...i} />))}
          </CardContainer>
          <button type='button' className={styles.side_btn}>
            <Image src='/Checklist.png' width={18} height={18} />
          </button>
          <button type='button' className={styles.side_btn2}>
            <Image src='/List.png' width={18} height={18} />
          </button>
        </main>
      </div>

    </>
  )
}
